# -*- coding: utf-8 -*-
"""25BAI0194 Exp4-28/07/26-Imputation Techniques

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i17WGjic8hBm3qCCnbM1pb863TRAxctD
"""

import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer
from IPython.display import display

df = pd.DataFrame(
    {
        "Age": [25, np.nan, 30, 45, 22],
        "Salary": [50000, 60000, np.nan, 80000, 45000],
        "Category": ["A", "B", "A", np.nan, "B"],
    }
)

display(df)

mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]]).flatten()
display(df[["Age", "Age_Mean"]])

median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]]).flatten()
display(df[["Salary", "Salary_Median"]])

mode_imputer = SimpleImputer(strategy="most_frequent")
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).flatten()
display(df[["Category", "Category_Mode"]])

num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = pd.DataFrame(
    mice_imputer.fit_transform(df[num_cols]),
    columns=num_cols
)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
display(df[["Age", "Salary", "Age_MICE", "Salary_MICE"]])

display(df)

import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer
from IPython.display import display

df = pd.DataFrame(
    {
        "Rooms": [3, np.nan, 2, 5, 4],
        "Price": [350000, 420000, np.nan, 680000, 510000],
        "Type": ["House", "Apartment", "House", np.nan, "Apartment"],
    }
)

display(df)

mean_imputer = SimpleImputer(strategy="mean")
df["Rooms_Mean"] = mean_imputer.fit_transform(df[["Rooms"]]).flatten()
display(df[["Rooms", "Rooms_Mean"]])

median_imputer = SimpleImputer(strategy="median")
df["Price_Median"] = median_imputer.fit_transform(df[["Price"]]).flatten()
display(df[["Price", "Price_Median"]])

mode_imputer = SimpleImputer(strategy="most_frequent")
df["Type_Mode"] = mode_imputer.fit_transform(df[["Type"]]).flatten()
display(df[["Type", "Type_Mode"]])

num_cols = ["Rooms", "Price"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = pd.DataFrame(
    mice_imputer.fit_transform(df[num_cols]),
    columns=num_cols
)
df["Rooms_MICE"] = df_mice["Rooms"]
df["Price_MICE"] = df_mice["Price"]
display(df[["Rooms", "Price", "Rooms_MICE", "Price_MICE"]])

display(df)