# -*- coding: utf-8 -*-
"""25BAI0194 Exp4-28/07/26-MissingValues

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19kX8bjF-NQV3brh4egn5qPHXzXVvi9tt
"""

import numpy as np
import pandas as pd

data = np.array([
    [100, 120, 150],
    [250, 200, 180],
    [300, 280, 260],
    [150, 140, 130],
    [200, 130, 50]
])
dfx = pd.DataFrame(data, index=['laptop', 'phone', 'tablet', 'watch', 'camera'], columns=['warehouse1', 'warehouse2', 'warehouse3'])

dfx['warehouse4'] = np.nan
dfx.loc['monitor'] = [110, 95, 80, 105]
dfx.loc['router'] = np.nan
dfx['warehouse5'] = np.nan
dfx.loc['laptop', 'warehouse4'] = 135

print("Base Dataframe (dfx)")
display(dfx)

display(dfx.isnull())

display(dfx.notnull())

display(dfx.isnull().sum())

display(dfx.isnull().sum().sum())

display(dfx.count())

print("Warehouse 4 Series")
display(dfx['warehouse4'])

print("\nWarehouse 4 Non-Null Mask")
display(dfx['warehouse4'].notnull())

print("\nWarehouse 4 with NaNs Dropped Directly")
display(dfx['warehouse4'].dropna())

print("\nDrop Rows with Any NaNs (Empties the Dataframe)")
display(dfx.dropna())

print("\nDrop Rows Where Entire Row contains NaNs")
display(dfx.dropna(how='all'))

print("\nDrop Columns Where Entire Column contains NaNs")
display(dfx.dropna(how='all', axis=1))

print("\nKeep Columns with at Least 5 Valid Values (thresh=5)")
display(dfx.dropna(thresh=5, axis=1))

ar1 = np.array([1000, 1500, np.nan, 2200])
ser1 = pd.Series(ar1)

print("NumPy Array Mean vs Pandas Series Mean")
print("NumPy Mean (propagates NaN):",{ar1.mean()})
print("Pandas Mean (ignores NaN):", {ser1.mean()})

ser2 = dfx['warehouse4']

print("\nWarehouse 4 Sum")
display(ser2.sum())

print("\nWarehouse 4 Average")
display(ser2.mean())

print("\nWarehouse 4 Cumulative Sum")
display(ser2.cumsum())

filledDf = dfx.fillna(0)

print("Dataframe Filled with 0")
display(filledDf)

print("\nOriginal Column Means")
display(dfx.mean())

print("\nZero-Filled Column Means")
display(filledDf.mean())

print("\nWarehouse 3 Forward Fill")
display(dfx['warehouse3'].ffill())

print("\nWarehouse 3 Backward Fill")
display(dfx['warehouse3'].bfill())

print("\nWarehouse 4 Forward Fill")
display(dfx['warehouse4'].ffill())

print("\nWarehouse 4 Backward Fill")
display(dfx['warehouse4'].bfill())

import numpy as np
import pandas as pd

data = np.array([
    [100, 120, 150],
    [250, 200, 180],
    [300, 280, 260],
    [150, 140, 130],
    [200, 130, 50]
])
dfx = pd.DataFrame(data, index=['laptop', 'phone', 'tablet', 'watch', 'camera'], columns=['warehouse1', 'warehouse2', 'warehouse3'])

dfx['warehouse4'] = np.nan
dfx.loc['monitor'] = [110, 95, 80, 105]
dfx.loc['router'] = np.nan
dfx['warehouse5'] = np.nan
dfx.loc['laptop', 'warehouse4'] = 135

dfx.isnull()
dfx.notnull()
dfx.isnull().sum()
dfx.isnull().sum().sum()
dfx.count()

dfx['warehouse4']
dfx['warehouse4'].notnull()
dfx['warehouse4'].dropna()

dfx.dropna()
dfx.dropna(how='all')
dfx.dropna(how='all', axis=1)
dfx.dropna(thresh=5, axis=1)

ar1 = np.array([1000, 1500, np.nan, 2200])
ser1 = pd.Series(ar1)
ar1.mean()
ser1.mean()

ser2 = dfx['warehouse4']
ser2.sum()
ser2.mean()
ser2.cumsum()

filledDf = dfx.fillna(0)
filledDf
dfx.mean()
filledDf.mean()

dfx['warehouse3'].ffill()
dfx['warehouse3'].bfill()


dfx['warehouse4'].ffill()
dfx['warehouse4'].bfill()

import numpy as np
import pandas as pd
from IPython.display import display

data = np.arange(15, 30).reshape(5, 3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi', 'grapes', 'mango'], columns=['store1', 'store2', 'store3'])

dfx['store4'] = np.nan
dfx.loc['watermelon'] = np.arange(15, 19)
dfx.loc['oranges'] = np.nan
dfx['store5'] = np.nan

dfx.loc['apple', 'store4'] = 20.0

display(dfx)

display(dfx.isnull())

display(dfx.notnull())

display(dfx.isnull().sum())

display(dfx.isnull().sum().sum())

display(dfx.count())

print("Store 4 Series Filtered with Boolean Mask")
display(dfx.store4[dfx.store4.notnull()])

print("\nStore 4 with NaNs Dropped Directly")
display(dfx.store4.dropna())

print("\nDrop Rows with Any NaNs (Empties the Dataframe)")
display(dfx.dropna())

print("\nDrop Rows Where Entire Row contains NaNs")
display(dfx.dropna(how='all'))

print("\nDrop Columns Where Entire Column contains NaNs")
display(dfx.dropna(how='all', axis=1))

print("\nKeep Columns with at Least 5 Valid Values (thresh=5)")
display(dfx.dropna(thresh=5, axis=1))

ar1 = np.array([100, 200, np.nan, 300])
ser1 = pd.Series(ar1)

print("NumPy Array Mean vs Pandas Series Mean")
print("NumPy Mean (propagates NaN):",ar1.mean())
print("Pandas Mean (ignores NaN):",{ser1.mean()})

ser2 = dfx.store4

print("\nStore 4 Sum")
display(ser2.sum())

print("\nStore 4 Average")
display(ser2.mean())

print("\nStore 4 Cumulative Sum")
display(ser2.cumsum())

filledDf = dfx.fillna(0)

print("Dataframe Filled with 0")
display(filledDf)

print("\nOriginal Column Means")
display(dfx.mean())

print("\nZero-Filled Column Means")
display(filledDf.mean())

print("\nStore 4 Forward Fill (ffill)")
display(dfx.store4.ffill())

print("\nStore 4 Backward Fill (bfill)")
display(dfx.store4.bfill())

import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer
from IPython.display import display

df = pd.DataFrame(
    {
        "Age": [25, np.nan, 30, 45, 22],
        "Salary": [50000, 60000, np.nan, 80000, 45000],
        "Category": ["A", "B", "A", np.nan, "B"],
    }
)

display(df)

mean_imputer = SimpleImputer(strategy="mean")
df["Age_Mean"] = mean_imputer.fit_transform(df[["Age"]]).flatten()
display(df[["Age", "Age_Mean"]])

median_imputer = SimpleImputer(strategy="median")
df["Salary_Median"] = median_imputer.fit_transform(df[["Salary"]]).flatten()
display(df[["Salary", "Salary_Median"]])

mode_imputer = SimpleImputer(strategy="most_frequent")
df["Category_Mode"] = mode_imputer.fit_transform(df[["Category"]]).flatten()
display(df[["Category", "Category_Mode"]])

num_cols = ["Age", "Salary"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = pd.DataFrame(
    mice_imputer.fit_transform(df[num_cols]),
    columns=num_cols
)
df["Age_MICE"] = df_mice["Age"]
df["Salary_MICE"] = df_mice["Salary"]
display(df[["Age", "Salary", "Age_MICE", "Salary_MICE"]])

display(df)

import numpy as np
import pandas as pd
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer, SimpleImputer
from IPython.display import display

# Sample dataset: Real Estate Properties
df = pd.DataFrame(
    {
        "Rooms": [3, np.nan, 2, 5, 4],
        "Price": [350000, 420000, np.nan, 680000, 510000],
        "Type": ["House", "Apartment", "House", np.nan, "Apartment"],
    }
)

display(df)

mean_imputer = SimpleImputer(strategy="mean")
df["Rooms_Mean"] = mean_imputer.fit_transform(df[["Rooms"]]).flatten()
display(df[["Rooms", "Rooms_Mean"]])

median_imputer = SimpleImputer(strategy="median")
df["Price_Median"] = median_imputer.fit_transform(df[["Price"]]).flatten()
display(df[["Price", "Price_Median"]])

mode_imputer = SimpleImputer(strategy="most_frequent")
df["Type_Mode"] = mode_imputer.fit_transform(df[["Type"]]).flatten()
display(df[["Type", "Type_Mode"]])

num_cols = ["Rooms", "Price"]
mice_imputer = IterativeImputer(max_iter=10, random_state=42)
df_mice = pd.DataFrame(
    mice_imputer.fit_transform(df[num_cols]),
    columns=num_cols
)
df["Rooms_MICE"] = df_mice["Rooms"]
df["Price_MICE"] = df_mice["Price"]
display(df[["Rooms", "Price", "Rooms_MICE", "Price_MICE"]])

display(df)