# -*- coding: utf-8 -*-
"""4/08/2026 25BAI0194 EDA EXPT 5

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qGvJ03WyuCssKX_E9WbncOTpZGdFrGC
"""

import io
import numpy as np
import pandas as pd
from google.colab import files
from sklearn.preprocessing import RobustScaler

print("STEP 1: UPLOAD YOUR CSV FILE ===")

uploaded = files.upload()

file_name = list(uploaded.keys())[0]
print(f"\nLoaded file: {file_name}")

df_cc = pd.read_csv(io.BytesIO(uploaded[file_name]))
print(f"Dataset Shape: {df_cc.shape}")
print("\n--- First 3 Rows ---")
print(df_cc.head(3))


amount_col = 'Amount'
label_col = 'Is_Fraud'


print(f"\n=== STEP 3: ROBUST SCALING ON '{amount_col}' ===")
robust_scaler = RobustScaler()
df_cc['Scaled_Amount'] = robust_scaler.fit_transform(df_cc[[amount_col]])


print("\n=== STEP 4: DETECTING OUTLIERS ===")
Q1 = df_cc[amount_col].quantile(0.25)
Q3 = df_cc[amount_col].quantile(0.75)
IQR = Q3 - Q1

upper_bound = Q3 + 1.5 * IQR
print(f"Normal Threshold Upper Limit: {upper_bound:.2f}")

outliers_df = df_cc[df_cc[amount_col] > upper_bound]
print(f"Total Outlier Transactions Detected: {len(outliers_df)}")


if label_col in df_cc.columns:
    print("\n=== STEP 5: FRAUD VS OUTLIER EVALUATION ===")
    true_positives = outliers_df[label_col].sum()
    total_fraud_in_file = df_cc[label_col].sum()
    false_positives = len(outliers_df) - true_positives

    print(f"Fraudulent Transactions caught as Outliers: {true_positives} / {total_fraud_in_file}")
    print(f"Legitimate Transactions flagged as Outliers: {false_positives}")
else:
    print(f"\n[Note]: Label column '{label_col}' not found. Skipping evaluation metric.")

print("\n--- Top Extreme Detected Outliers ---")
print(outliers_df.sort_values(by=amount_col, ascending=False).head(10))