# -*- coding: utf-8 -*-
"""ayushi194eda3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sV560gljhcH9RxVSjMKTD-vFhsmsONzZ
"""

import pandas as pd
df1SE = pd.DataFrame({'StudentID': [101, 103, 105, 107, 109, 111, 113, 115, 117, 119],
                      'ScoreSE': [85, 92, 78, 64, 88, 91, 73, 82, 69, 95]})
df2SE = pd.DataFrame({'StudentID': [102, 104, 106, 108, 110, 112, 114, 116, 118, 120],
                      'ScoreSE': [72, 81, 65, 90, 87, 76, 83, 94, 61, 89]})
df1ML = pd.DataFrame({'StudentID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
                      'ScoreML': [89, 74, 91, 85, 76, 70, 62, 93, 85, 88]})
df2ML = pd.DataFrame({'StudentID': [111, 112, 113, 114, 115, 121, 122, 123, 124, 125],
                      'ScoreML': [90, 80, 75, 88, 81, 95, 77, 68, 84, 91]})

dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)
df = dfSE.merge(dfML, how='inner', on='StudentID')
print(df)

dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)
df = dfSE.merge(dfML, how='inner')
print(df)

dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)
df = dfSE.merge(dfML, how='left')
print(df)

dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)
df = dfSE.merge(dfML, how='right')
print(df)

se_students = set(pd.concat([df1SE, df2SE])['StudentID'])
ml_students = set(pd.concat([df1ML, df2ML])['StudentID'])

total_students = len(se_students.union(ml_students))
only_SE = len(se_students.difference(ml_students))
only_ML = len(ml_students.difference(se_students))

print("How many students appeared for the exams in total?", total_students)
print("How many students only appeared for the Software Engineering course?",only_SE)
print("How many students only appeared for the Machine Learning course?",only_ML)

df['TotalScore'] = df['ScoreSE'] + df['ScoreML']
df.head(10)

import numpy as np
import pandas as pd

data = np.arange(15).reshape((3, 5))
indexers = ['Rainfall', 'Humidity', 'Wind']
columns = ['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand']

dframe1 = pd.DataFrame(data, index=indexers, columns=columns)
print("Original DataFrame")
print(dframe1)

stacked = dframe1.stack()
print("\nStacked Series")
print(stacked)

unstacked_dframe1 = stacked.unstack()
print("\nUnstacked DataFrame")
print(unstacked_dframe1)


series1 = pd.Series([0, 111, 222, 333], index=['zeros', 'ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])

unstacked_frame2 = frame2.unstack()
print("\nUnstacked frame2 DataFrame")
print(unstacked_frame2)